### ISSUE TITLE
crash when validating `lead.emailaddress1`

### ISSUE THREAD

**Issue by skfd** [mattybeard/DataExportValidationChecker#11]
There is not much detail, sorry.

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidCastException: Specified cast is not valid.
   at DataExportValidationChecker.DataExportValidationCheckerPluginControl.<>c__DisplayClass17_0.<CalculateValidation>b__2(RunWorkerCompletedEventArgs args)
   at XrmToolBox.Extensibility.Worker.<>c__DisplayClass4_0.<WorkAsync>b__0(Object s, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
```

**Comment by mattybeard** [comment]
Fixed in #12
